name: Compile Pages
on: [push]
jobs:
  compile-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run deploy
